package com.faderw.school.dao;

import com.faderw.school.domain.Area;
import org.apache.ibatis.jdbc.SQL;

public class AreaSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area
     *
     * @mbg.generated 2018-07-17 15:49:48
     */
    public String insertSelective(Area record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_area");
        
        if (record.getAreaId() != null) {
            sql.VALUES("area_id", "#{areaId,jdbcType=INTEGER}");
        }
        
        if (record.getAreaName() != null) {
            sql.VALUES("area_name", "#{areaName,jdbcType=VARCHAR}");
        }
        
        if (record.getPriority() != null) {
            sql.VALUES("priority", "#{priority,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    public String listArea() {
        SQL sql = new SQL();
        sql.SELECT("area_id")
                .SELECT("area_name")
                .SELECT("priority")
                .SELECT("create_time")
                .SELECT("update_time");

        sql.FROM("tb_area");

        return sql.toString();
    }
}